### ISSUE TITLE
Any plan to open-source?

### ISSUE THREAD

**Issue by samiptimalsena** [ramsrigouthamg/Supertranslate.ai#1]
Eagerly waiting :D

**Comment by ramsrigouthamg** [comment]
Hi Samip,
These are part of open-source initiatives!
The first one released is a colab notebook to burn subtitles into videos.
Slowly will add more - creating motion graphics with text, auto subtitling (smart splitting)  etc

**Comment by milsun** [comment]
Any pointers as to how to deal with whisper hallucinations, accurate word timestamps, speaker diarization?
